-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 21:32:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `id_Produtos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `referencia` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `unidade` VARCHAR(45) NULL,
  `fornecedores` VARCHAR(45) NULL,
  `custo` VARCHAR(45) NULL,
  `venda` VARCHAR(45) NULL,
  `quantidade` VARCHAR(45) NULL,
  `estoqueAtual` VARCHAR(45) NULL,
  `caminho` VARCHAR(45) NULL,
  `dataLancamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Produtos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id_Clientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `apelido` VARCHAR(45) NULL,
  `cpf` VARCHAR(14) NULL,
  `rg` VARCHAR(15) NULL,
  `emissor` VARCHAR(10) NULL,
  `Nascimento` VARCHAR(10) NULL,
  `rua` VARCHAR(45) NULL,
  `qd` VARCHAR(4) NULL,
  `lt` VARCHAR(4) NULL,
  `n` VARCHAR(4) NULL,
  `bairro` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `telefone` VARCHAR(15) NULL,
  `identificacao` VARCHAR(45) NULL,
  `email` VARCHAR(200) NULL,
  `pai` VARCHAR(100) NULL,
  `mae` VARCHAR(100) NULL,
  `responsavel` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `observacao` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_Clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdemServico` (
  `idOrdemdeServico` INT NOT NULL AUTO_INCREMENT,
  `caminhoOS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrdemdeServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FormaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FormaPagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataVencimento` VARCHAR(45) NULL,
  `formaPagamento` VARCHAR(45) NULL,
  `valorRestante` VARCHAR(45) NULL,
  `quantParcelas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auditoria` (
  `idauditoria` INT NOT NULL AUTO_INCREMENT,
  `tabela` VARCHAR(45) NOT NULL,
  `campoModificado` VARCHAR(45) NOT NULL,
  `valorAnterior` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idauditoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Produtos_id_Produtos` INT NOT NULL,
  `Clientes_id_Clientes` INT NOT NULL,
  `FormaPagamento_idPagamento` INT NOT NULL,
  `OrdemServico_idOrdemdeServico` INT NULL,
  `dataCompra` VARCHAR(45) NULL,
  PRIMARY KEY (`Produtos_id_Produtos`, `Clientes_id_Clientes`, `FormaPagamento_idPagamento`),
  INDEX `fk_Produtos_has_Clientes_Clientes1_idx` (`Clientes_id_Clientes` ASC),
  INDEX `fk_Produtos_has_Clientes_Produtos_idx` (`Produtos_id_Produtos` ASC),
  INDEX `fk_Compra_FormaPagamento1_idx` (`FormaPagamento_idPagamento` ASC),
  INDEX `fk_Compra_OrdemServico1_idx` (`OrdemServico_idOrdemdeServico` ASC),
  CONSTRAINT `fk_Produtos_has_Clientes_Produtos`
    FOREIGN KEY (`Produtos_id_Produtos`)
    REFERENCES `mydb`.`Produtos` (`id_Produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Clientes_Clientes1`
    FOREIGN KEY (`Clientes_id_Clientes`)
    REFERENCES `mydb`.`Clientes` (`id_Clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_FormaPagamento1`
    FOREIGN KEY (`FormaPagamento_idPagamento`)
    REFERENCES `mydb`.`FormaPagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_OrdemServico1`
    FOREIGN KEY (`OrdemServico_idOrdemdeServico`)
    REFERENCES `mydb`.`OrdemServico` (`idOrdemdeServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


show tables;
select * from produtos;
USE `mydb` ;
select * from clientes where nome like '%%' or cpf like '%%';
